---

- name: Clone or update env repo
  git:
    repo: "{{ env_repo }}"
    dest: "{{ env_path }}"
    version: "{{ env_version | default('master') }}"
    update: no

# Clone as root then fix permissions to allow SSH agent forwarding to work.
- name: Fix env repo permissions
  file:
    path: "{{ env_path }}"
    owner: "{{ env_user }}"
    group: "{{ env_group }}"
    recurse: true
